### ISSUE TITLE
Reviewer 1 comments

### ISSUE THREAD

**Issue by jvcasillas** [RAP-group/empathy_intonation_perc#27]
Reviewer: 1

Comments to the Author
INTRODUCTION AND OBJECTIVES

1. [x] https://github.com/RAP-group/empathy_intonation_perc/issues/31. The terms perception, processing and comprehension are used in the manuscript not very systematically. In some cases the authors use “perception and processing” together, and in some others they seem to summarize them both in the term “comprehension”. A more systematic use of these terms is needed.

2. [x] https://github.com/RAP-group/empathy_intonation_perc/issues/32. The authors used distinct terms to refer to the same sentence type: absolute interrogative, polar question, yes/no question, total interrogative… It also alternates between the term ‘statement’ and the term ‘declarative’. It recommends using one term in a systematic way and to describe and exemplify what these terms mean for readers that are not experts on intonation (or syntax or pragmatics). The authors now provide some general description of the intonational patterns in the introduction (e.g. ‘nuclear hat pattern’, ‘final rise’, but I doubt whether a reader that is not an expert on intonation will understand these descriptions). 

3. [x] https://github.com/RAP-group/empathy_intonation_perc/issues/33. The introduction mentions several times that “intonation may result in comprehension and communication difficulties” and that “interpreting L2 intonation is challenging”, and it feels a bit repetitive. These statements should also be better motivated and better justified (intonation more than other linguistic aspects? which kind of difficulties? what does ‘challenging’ mean? why is it challenging? all intonation patterns work equally?). 

4. [x] https://github.com/RAP-group/empathy_intonation_perc/issues/34. The factor “speaker dialectal variety” seems to appear and disappear from the manuscript. The introduction includes a paragraph on dialectal variance in Spanish intonation, and it is included as a third research question, but the authors should elaborate further on why dialectal variance may affect the processing of L2 intonation or even if it may affect learning. In the discussion and conclusion this factor is not mentioned when the authors summarize the aims of the study at the beginning of these sections. In sum, one feels that this research question is not well integrated into the study (or at least the manuscript). 

5. [x] https://github.com/RAP-group/empathy_intonation_perc/issues/35. The study explores 4 specific sentence types that differ at the intonation level. The authors should motivate the selection of these sentence types, describe them at the intonational level for all varieties used, and elaborate on why certain sentence types are more difficult to process for L2 learners and, more specifically, for English learners of Spanish. Otherwise it is not possible to understand the nature of the differences that had to be perceived by the participants of the study and that, more generally, have to be learned in an L2. 

6. [x] https://github.com/RAP-group/empathy_intonation_perc/issues/36. Also, why empathy should play a role in how these specific sentence types are perceived and processed? Why do the authors think that the listeners’ ability to feel/think what the other feel/think may impact in distinguishing questions from statements? In other words: what are the intonational cues in a declarative or in a yes/no question that may lead to distinct processing accuracy and speech by listeners with distinct empathy skills? Please motivate these aspects further. 

7. [x] https://github.com/RAP-group/empathy_intonation_perc/issues/37. Please elaborate and motivate further why you think that empathy may lead to higher/faster intonational development in an L2 (expectation for RQ2). Likewise, please motivate further your expectations for RQ3, as they are now somehow disconnected from the literature reviewed in the introduction. The authors mention that statements might be more difficult to differentiate from questions in the Cuban variety, but without information on why this must be the case (a distinct intonational pattern for certain questions, maybe?) it is impossible to evaluate whether this expectation makes sense. 

STIMULI

8. [x] https://github.com/RAP-group/empathy_intonation_perc/issues/38. Details on the stimuli used for the experimental task are much needed. Please describe the sentences used at the acoustic and phonological level, for all varieties, and provide a list of these sentences. Importantly, were they controlled at the syntactic and lexical levels to ensure that potential differences in processing speed were not due to syntactic or lexical factors? On a related note, and crucially to interpret your results, how can we be sure that listeners responded based on the intonational cues they perceived and not on potential syntactic and lexical cues in the sentences?

9. [x] https://github.com/RAP-group/empathy_intonation_perc/issues/39. Please provide the results of the 100 monolingual Spanish speakers rating the quality of items.

10. [x] https://github.com/RAP-group/empathy_intonation_perc/issues/40. Please provide details on which variety the listeners were familiar with, and put these data in relation to the participants’ responses in the results in a more systematic way.

RESULTS & DISCUSSION

11. [x] https://github.com/RAP-group/empathy_intonation_perc/issues/41. Results show that proficiency and empathy interact in wh-questions but not in yes/no questions or declaratives, and that empathy had an effect in all sentence types except for yes/no question. There is no discussion on how these findings relate to previous literature on sentence comprehension, or even on what may originate these differences across sentence types. Instead, the discussion and conclusion now seem to mask these differences across sentence types. 

12. [x] https://github.com/RAP-group/empathy_intonation_perc/issues/42. Could you check whether individuals with higher empathy were not the ones with higher proficiency? How did these two factors correlate?

13. [x] https://github.com/RAP-group/empathy_intonation_perc/issues/43. In the discussion the authors highlight the fact that proficiency was treated as a continuous variable, and the reader would benefit from knowing whether this is actually an innovation of the present study or if, instead, other studies have done it before (now it seems that it is an innovation). 

14. [x] https://github.com/RAP-group/empathy_intonation_perc/issues/44. The authors try to explain the variety-specific responses by providing three hypotheses. However, I think that none of these hypotheses are sufficiently motivated or explained. First, they state that “familiarity with the target variety may account for variety-specific response accuracy”, although this cannot be derived from the results you obtained since most of your listeners were most familiar with US Spanish (which was not in the stimuli). Second, they state that they may derive from the fact that distinct varieties produce each sentence type using distinct intonational patterns, although it is impossible to evaluate if this hypothesis is plausible because details on the intonational features of the stimuli are missing and because results are never matched to the nature of the contour that was perceived. Finally, the authors propose an explanation linked to the distinct speech rate used in distinct varieties. The authors should provide a detailed description of the speech rate of the stimuli, by variety, in order for the reader to be able to evaluate if this explanation is indeed plausible. All in all, I recommend the authors to adjust the discussion of the effect of listener/speaker variety to the results that were actually obtained, and to provide enough details of the stimuli to ensure the reader can assess the validity of these explanations.
