### ISSUE TITLE
Tasks for co-authors

### ISSUE THREAD

**Issue by jvcasillas** [RAP-group/empathy_intonation_perc#30]
- [x] reread manuscript (preprint here: https://psyarxiv.com/e5vk2/)
- [x] read Associate editor decision (https://github.com/RAP-group/empathy_intonation_perc/issues/26)
- [x] read Reviewer 1 comments (https://github.com/RAP-group/empathy_intonation_perc/issues/27)
- [x] read Reviewer 2 comments (https://github.com/RAP-group/empathy_intonation_perc/issues/28)
- [x] read Reviewer 3 comments (https://github.com/RAP-group/empathy_intonation_perc/issues/29)
- [x] peruse all open issues and assign yourself to ones you think you can contribute to (if not sure, ask)
